"""create streamer_rank table

Revision ID: 799ccd1e8029
Revises: 69223a4df39d
Create Date: 2025-05-19 21:23:37.743928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799ccd1e8029'
down_revision: Union[str, None] = '69223a4df39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streamer_rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streamer', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('league_points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streamer_rank_id'), 'streamer_rank', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streamer_rank_id'), table_name='streamer_rank')
    op.drop_table('streamer_rank')
    # ### end Alembic commands ###
